//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by gazo.rc
//
#define IDC_RECONST_QUEUE               3
#define IDC_HISTG_QUEUE                 3
#define IDC_REFR_SHOW                   3
#define IDC_RECONST_STOP                4
#define IDC_HISTG_GETPATH               4
#define IDC_REFR_STOP                   4
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_GAZOTYPE                    129
#define IDD_RECONST                     130
#define IDD_HISTOGRAM                   132
#define IDC_CURSOR_WHEEL                133
#define IDD_QUEUE                       134
#define IDR_MENU_POPUP                  135
#define IDD_MESSAGE                     136
#define IDD_PROPERTY                    137
#define IDD_RECON_OPT                   138
#define IDD_HISTO_OPT                   139
#define IDD_REFRACTION                  140
#define IDD_LSQFIT                      141
#define IDD_HORIZCENTER                 142
#define IDD_RENUMFILES                  143
#define IDD_GENERAL                     144
#define IDD_OVERLAY                     145
#define IDD_RESOLNPLOT                  146
#define IDD_FRAMELIST                   147
#define IDD_DIALBOX                     148
#define IDC_RECONST_SLICE1              1000
#define IDC_RECONST_CENT1               1001
#define IDC_RECONST_SLICE2              1002
#define IDC_RECONST_CENT2               1003
#define IDC_RECONST_BATCH               1004
#define IDC_RECONST_SLICE3              1004
#define IDC_RECONST_OFFAXIS             1004
#define IDC_RECONST_INTP                1005
#define IDC_RECONST_PIXEL               1006
#define IDC_RECONST_HISDATASET          1006
#define IDC_RECONST_AUTO1               1007
#define IDC_RECONST_AUTO2               1008
#define IDC_RECONST_SUFFIX              1009
#define IDC_RECONST_SINO1               1009
#define IDC_RECONST_FILTER              1010
#define IDC_RECONST_HISDATASET2         1010
#define IDC_RECONST_SHOW1               1011
#define IDC_RECONST_SUFFIX2             1011
#define IDC_RECONST_TRIM                1011
#define IDC_RECONST_SHOW2               1012
#define IDC_RECONST_OUTPATH             1012
#define IDC_RECONST_CUTOFF              1013
#define IDC_RECONST_SUFFIX3             1013
#define IDC_RECONST_ORDER               1014
#define IDC_RECONST_PROGRESS            1015
#define IDC_RECONST_DRIFTLISTPATH       1015
#define IDC_HISTG_BITMAP                1016
#define IDC_RECONST_TILT                1016
#define IDC_RECONST_RESOLN              1017
#define IDC_RECONST_SELECT              1017
#define IDC_HISTG_HSTMAX                1018
#define IDC_HISTG_HSTLOW                1019
#define IDC_HISTG_HSTHIGH               1020
#define IDC_HISTG_MAG                   1021
#define IDC_HISTG_HSTUNIT               1022
#define IDC_HISTG_CURSLOW               1023
#define IDC_HISTG_CURSHIGH              1024
#define IDC_HISTG_PREVIEW               1025
#define IDC_HISTG_TRMCENTX              1026
#define IDC_HISTG_TRMCENTY              1027
#define IDC_HISTG_TRMSIZEX              1028
#define IDC_HISTG_TRMSIZEY              1029
#define IDC_HISTG_TRMANGLE              1030
#define IDC_HISTG_HSTHIGH2              1031
#define IDC_HISTG_STAT                  1031
#define IDC_HISTG_PREFIX                1032
#define IDC_HISTG_PROGRESS              1033
#define IDC_HISTG_TRMAVRG               1034
#define IDC_HISTG_ENTRIM                1035
#define IDC_HISTOPT_RMDEPTH             1035
#define IDC_HISTG_FILEMSG               1036
#define IDC_HISTOPT_RMLAC               1036
#define IDC_QUEUE_LIST                  1037
#define IDC_HISTG_BOXMSG                1037
#define IDC_QUEUE_STOP                  1038
#define IDC_HISTG_16BIT                 1038
#define IDC_QUEUE_FINAL                 1039
#define IDC_MSG_TEXT                    1040
#define IDC_PROP_CPU                    1042
#define IDC_PROP_NCPU                   1042
#define IDC_PROP_CPU2                   1043
#define IDC_PROP_MEMORY                 1043
#define IDC_CHECK1                      1044
#define IDC_PROP_SIMD                   1044
#define IDC_RECONST_OFFCT               1044
#define IDC_RECONST_ANGINTP             1044
#define IDC_MOVE1                       1044
#define IDC_RESOLNPLOT_PLOTR            1044
#define IDC_PROP_INTELCPU               1045
#define IDC_RECONST_ZERNIKE             1045
#define IDC_MOVE2                       1045
#define IDC_RESOLNPLOT_PLOTG            1045
#define IDC_CUDAGPU                     1046
#define IDC_PROP_CUDAGPU                1046
#define IDC_MOVE3                       1046
#define IDC_RECONST_SKIPPREWHITE        1046
#define IDC_RESOLNPLOT_PLOTB            1046
#define IDC_PROP_GPU                    1047
#define IDC_PROP_NGPU                   1047
#define IDC_MOVE4                       1047
#define IDC_PROP_CUDABLOCK              1048
#define IDC_PROP_CUDANBLOCK             1048
#define IDC_OVLY_CHKW1                  1048
#define IDC_PROP_ENREPORT               1049
#define IDC_OVLY_CHKW2                  1049
#define IDC_RECONST_OPTIONS             1050
#define IDC_PROP_SIMD2                  1050
#define IDC_PROP_CUDAFFT                1050
#define IDC_OVLY_CHKW3                  1050
#define IDC_HISTG_OPT                   1051
#define IDC_PROP_ATISTREAM              1051
#define IDC_OVLY_CHKW4                  1051
#define IDC_BUTTON1                     1052
#define IDC_RECONST_SETPATH             1052
#define IDC_PROP_NGPU2                  1052
#define IDC_PROP_NATISTREAM             1052
#define IDC_LSQFIT_REFSET               1052
#define IDC_RESOLNPLOT_UPDATE           1052
#define IDC_REFR_ATOMZ                  1053
#define IDC_PROP_CUDANBLOCK2            1053
#define IDC_PROP_ATINWORK               1053
#define IDC_PROP_ATISTREAMNWORK         1053
#define IDC_LSQFIT_QRYSET               1053
#define IDC_RECONST_SETDRIFTLIST        1053
#define IDC_REFR_ATOMA                  1054
#define IDC_PROP_ENFASTSEEK             1054
#define IDC_REFR_DENSITY                1055
#define IDC_REFR_LAC                    1056
#define IDC_REFR_XENERGY                1057
#define IDC_REFR_S2DDIST                1058
#define IDC_REFR_PXSIZE                 1059
#define IDC_REFR_STATUS                 1060
#define IDC_REFR_PXSIZE2                1061
#define IDC_REFR_PREFIX                 1061
#define IDC_RECONST_DRSTART             1061
#define IDC_RECONST_DREND               1062
#define IDC_RECONST_DRX                 1063
#define IDC_RECONST_DRY                 1064
#define IDC_CHECK2                      1065
#define IDC_RECONST_OMIT                1065
#define IDC_LSQFIT_REFLIST              1066
#define IDC_RECONST_DRIFTPARAMS         1066
#define IDC_LSQFIT_REFMSG               1067
#define IDC_RECONST_DRIFTLIST           1067
#define IDC_LSQFIT_START                1068
#define IDC_LSQFIT_RESULT               1069
#define IDC_LSQFIT_QRYLIST              1070
#define IDC_LSQFIT_QRYMSG               1071
#define IDC_LSQFIT_XLOW                 1072
#define IDC_LSQFIT_XHIGH                1073
#define IDC_LSQFIT_YLOW                 1074
#define IDC_LSQFIT_YHIGH                1075
#define IDC_HORIZCEN_SAVE               1075
#define IDC_RENUM_FILELIST              1075
#define IDC_LSQFIT_ZLOW                 1076
#define IDC_HORIZCEN_BACK               1076
#define IDC_LSQFIT_ZHIGH                1077
#define IDC_HORIZCEN_GETLIST            1077
#define IDC_RENUM_MSG                   1077
#define IDC_LSQFIT_STOP                 1078
#define IDC_RENUM_SETFILE               1078
#define IDC_HORIZCEN_AVG                1078
#define IDC_RENUM_PREFIX                1079
#define IDC_LSQFIT_START2               1079
#define IDC_LSQFIT_QUEUE                1079
#define IDC_RENUM_STARTINDEX            1080
#define IDC_RENUM_OUTPATH               1081
#define IDC_RENUM_SETPATH               1082
#define IDC_RADIO_RELATIVE              1083
#define IDC_RENUM_ROTZ                  1083
#define IDC_RADIO2                      1084
#define IDC_RADIO_ABSOLUTE              1084
#define IDC_RENUM_ROTY                  1084
#define IDC_RECONST_FRAMEODD            1084
#define IDC_ABOUT_VER                   1085
#define IDC_RENUM_ROTY2                 1085
#define IDC_RENUM_ROTX                  1085
#define IDC_RECONST_FRAMEODD2           1085
#define IDC_RECONST_FRAMEEVEN           1085
#define IDC_RECONST_FRAMEALL            1087
#define IDC_INPUT1                      1088
#define IDC_CAPTION1                    1089
#define IDC_CAPTION2                    1090
#define IDC_INPUT2                      1091
#define IDC_OVLYUP                      1091
#define IDC_CAPTION3                    1092
#define IDC_OVLYDOWN                    1092
#define IDC_INPUT3                      1093
#define IDC_OVLYLEFT                    1093
#define IDC_OVLYX1                      1094
#define IDC_OVLYY1                      1095
#define IDC_OVLYX2                      1096
#define IDC_OVLYY2                      1097
#define IDC_OVLYX3                      1098
#define IDC_OVLYY3                      1099
#define IDC_OVLYX4                      1100
#define IDC_OVLYY4                      1101
#define IDC_OVLYU1                      1102
#define IDC_OVLYV1                      1103
#define IDC_OVLYU2                      1104
#define IDC_OVLYV2                      1105
#define IDC_OVLYU3                      1106
#define IDC_OVLYV3                      1107
#define IDC_OVLYU4                      1108
#define IDC_OVLYV4                      1109
#define IDC_OVLY_APPLY                  1110
#define IDC_OVLYRIGHT                   1111
#define IDC_RECONST_SKIPINITIALFLATSINHDF5 1111
#define IDC_OVLYCW                      1112
#define IDC_RESOLNPLOT_BITMAP           1112
#define IDC_OVLYCCW                     1113
#define IDC_RESOLNPLOT_MAG              1113
#define IDC_OVLYLARGE                   1114
#define IDC_RESOLNPLOT_MSG              1114
#define IDC_OVLYW1                      1115
#define IDC_RESOLNPLOT_YHIGH            1115
#define IDC_OVLYSMALL                   1116
#define IDC_RESOLNPLOT_YLOW             1116
#define IDC_OVLYW2                      1117
#define IDC_RESOLNPLOT_PIXELWIDTH       1117
#define IDC_OVLYW3                      1118
#define IDC_RESOLNPLOT_CSV              1118
#define IDC_OVLYW4                      1119
#define IDC_OVLY_WUP                    1120
#define IDC_OVLY_ZDOWN                  1121
#define IDC_OVLY_WDOWN                  1121
#define IDC_TREE1                       1122
#define IDC_FRAMELIST_TREE              1122
#define IDC_DIALBOX_COMPORT             1414
#define IDC_DIALBOX_CONNECT             1415
#define IDC_DIALBOX_DISCONNECT          1416
#define IDC_DIALBOX_DIAL0CW             1417
#define IDC_DIALBOX_DIAL0CCW            1418
#define IDC_DIALBOX_DIAL0ACT            1419
#define IDC_DIALBOX_DIAL1ACT            1420
#define IDC_DIALBOX_DIAL2ACT            1421
#define IDC_DIALBOX_DIAL3ACT            1422
#define IDC_DIALBOX_DIAL4ACT            1423
#define IDC_DIALBOX_DIAL1ACT2           1424
#define IDC_DIALBOX_DIAL5ACT            1424
#define IDC_DIALBOX_RX                  1425
#define IDC_DIALBOX_DIAL3CW             1426
#define IDC_DIALBOX_DIAL3CCW            1427
#define IDC_DIALBOX_DIAL2CW             1428
#define IDC_DIALBOX_DIAL2CCW            1429
#define IDC_DIALBOX_DIAL1CW             1430
#define IDC_DIALBOX_DIAL1CCW            1431
#define IDC_DIALBOX_DIAL4CW             1432
#define IDC_DIALBOX_DIAL4CCW            1433
#define IDC_DIALBOX_DIAL0CW2            1434
#define IDC_DIALBOX_DIAL5CW             1434
#define IDC_DIALBOX_DIAL5CCW            1435
#define IDC_DIALBOX_BUTTON1ACT          1438
#define IDC_DIALBOX_BUTTON1REL          1439
#define IDC_DIALBOX_BUTTON2ACT          1440
#define IDC_DIALBOX_BUTTON2REL          1441
#define ID_TOOLBAR_MAG                  32771
#define ID_TOOLBAR_MIN                  32772
#define ID_TOOLBAR_DARK                 32773
#define ID_TOOLBAR_BRIGHT               32774
#define ID_TOOLBAR_CNTUP                32775
#define ID_TOOLBAR_CNTDOWN              32776
#define IDM_TOMO_RECONST                32777
#define IDM_HLP_DEBUG                   32778
#define IDM_TOMO_HISTG                  32779
#define IDM_TOMO_SAVE                   32780
#define IDM_TOMO_QUEUE                  32780
#define ID_TOOLBAR_FNFWD                32781
#define ID_TOOLBAR_FNFF                 32782
#define ID_TOOLBAR_FNREV                32783
#define ID_TOOLBAR_FNFR                 32784
#define ID_POPUPQUEUE_UP                32785
#define ID_POPUPQUEUE_DOWN              32786
#define IDM_TOMO_AXIS                   32787
#define ID_TOOLBAR_FNSF                 32788
#define ID_TOOLBAR_FNSR                 32789
#define IDM_TOMO_STAT                   32790
#define IDM_TOMO_LINE                   32791
#define ID_EDIT_PROPERTY                32792
#define ID_FILE_PROPERTY                32793
#define ID_TOMOGRAPHY_PROPERTY          32794
#define IDM_TOMO_PROPERTY               32795
#define ID_FILE_PREPAREFILES            32796
#define IDM_FILE_PREPFILES              32797
#define IDM_TOMO_REFRAC                 32798
#define ID_TOMOGRAPHY_LSQFITTING        32799
#define IDM_TOMO_LSQFIT                 32800
#define ID_TOMOGRAPHY_COMMENT           32801
#define IDM_TOMO_COMMENT                32802
#define IDM_FILE_CLOSEALL               32803
#define ID_TOMOGRAPHY_LATERAL           32804
#define IDM_TOMO_HORIZCENT              32805
#define IDM_TOMO_RENUMFILES             32806
#define IDM_VIEW_ERROR                  32807
#define ID_TOOLBAR_FNJUMPR              32808
#define ID_TOOLBAR_FNJUMPF              32809
#define ID_TOOLBAR_PLPAUSE              32810
#define ID_TOOLBAR_FNREVONE             32811
#define ID_TOOLBAR_FNFWDONE             32812
#define ID_TOMOGRAPHY_RESOLUTIONREPORT  32813
#define IDM_TOMO_FOURIER                32814
#define IDM_FILE_SAVEQUEUE              32815
#define IDM_FILE_LOADQUEUE              32816
#define IDM_VIEW_BOXAXISLABEL           32817
#define IDM_VIEW_DRAGSCROLL             32818
#define ID_TOMOGRAPHY_GAUSSIANCONVOLUTION 32819
#define ID_ANALYSIS_ADDNOISE            32820
#define IDM_OVERLAY                     32821
#define ID_FILE_DIALBOX                 32822
#define ID_ACCKEY_A                     32823
#define ID_ACCKEY_S                     32825
#define ID_ACCKEY_Z                     32826
#define ID_ACCKEY_X                     32827
#define ID_ACCKEY_Q                     32828
#define ID_ACCKEY_W                     32829
#define ID_ACCKEY_E                     32830
#define ID_ACCKEY_R                     32831
#define ID_ACCKEY_D                     32832
#define ID_ACCKEY_F                     32833
#define ID_ACCKEY_C                     32834
#define ID_ACCKEY_V                     32835
#define ID_ACCKEY_T                     32837
#define ID_ACCKEY_G                     32838
#define ID_POPUPQUEUE_DEL               32860

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32839
#define _APS_NEXT_CONTROL_VALUE         1125
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
